application-prod:
  yml:
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/mockit}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:thdtjdghks@}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Flyway 도입 후 validate/none 으로 전환 예정
    show-sql: true

  flyway:
    baseline-on-migrate: true

  security:
    oauth2:
      client: { }  # 카카오는 나중에...

  sql:
    init:
      mode: always
      data-locations: classpath:data-dev.sql


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
