server:
  port: 8080
  forward-headers-strategy: framework

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:.env.${spring.profiles.active}[.properties]

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  data:
    redis:
      repositories:
        enabled: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            client-secret: ""
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - profile_image
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: ${JWT_SECRET:__dev_only_change_me__}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000

management:
  metrics:
    enable:
      process.cpu: false

logging:
  level:
    org.hibernate.SQL: info
